### ISSUE TITLE
Module not found: Error: Default condition should be last one

### ISSUE THREAD

**Issue by rrrship** [timohausmann/quadtree-ts#12]
I think this issue was introduced with the [2.0.1 release](https://github.com/timohausmann/quadtree-ts/commit/53c6a894494adf67464ae99b4a77da1141ce2615). The "default" value in the package.json should be the last item of the object.

I'm using TS with Webpack. When I converted back to 2.0.0, then everything works fine.

**Comment by timohausmann** [comment]
Thanks for the info, pushed a fix (2.2.2)
https://github.com/timohausmann/quadtree-ts/commit/d1c278e7baec81a41f65c69013c20c960b878d90#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

https://www.npmjs.com/package/@timohausmann/quadtree-ts?activeTab=versions

Please let me know if it works for you.

**Comment by rrrship** [comment]
Yep, seems to be working fine. Thanks a lot!
