### ISSUE TITLE
Adding a licence file

### ISSUE THREAD

**Issue by egel** [timohausmann/quadtree-ts#5]
Hello Timo,

I also reported this to the JS version of the library [here](https://github.com/timohausmann/quadtree-js/issues/19) but forgot to mention it here 😆. It would be great if we could add the LICENSE file here.

As always if you're out of time atm, I would be happy to prepare a PR for you 🙂

Best,
Maciej

**Comment by timohausmann** [comment]
Hey, thank you, if you find the time, a PR with a MIT LICENSE.md similar to quadtree-js would be appreciated!

**Comment by timohausmann** [comment]
https://github.com/timohausmann/quadtree-ts/commit/e652e157d605b029beede2fc0dbd994dc9fa6180
