### ISSUE TITLE
ESM and types missing issue with 2.0.0 release

### ISSUE THREAD

**Issue by mundmische** [timohausmann/quadtree-ts#9]
We are having trouble including the 2.0.0 version you recently released.

We were able to fix the issue by adding the following line to the exports in the package.json:

```
  "exports": {
    ...
    "types": "./types/index.esm.d.ts"
  }
```

**Comment by timohausmann** [comment]
Thanks for the suggestion, added that line: https://github.com/timohausmann/quadtree-ts/commit/53c6a894494adf67464ae99b4a77da1141ce2615#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

and published: https://www.npmjs.com/package/@timohausmann/quadtree-ts?activeTab=versions

**Comment by mundmische** [comment]
Thank you very much. That is highly appreciated!

**Comment by timohausmann** [comment]
You're welcome, let me know if the issue persists.
